// MapboxMap.indoor is marked experimental in mapbox_maps_flutter 3.0.0.
// ignore_for_file: experimental_member_use

import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart';

import 'markers_page.dart';

/// Flutter port of the Mapbox GL JS example
/// "Add an indoor map with custom data":
/// https://docs.mapbox.com/mapbox-gl-js/example/indoor-mapping-custom-data/
/// shown here with a schematic plan of CityCube Berlin, the venue of
/// NEXTAPP 26, across its four event levels, with the Mapbox booth
/// (number 8 on level 2) highlighted.
///
/// The map loads Mapbox Standard as usual and adds the indoor fragment,
/// bundled as an asset, with [MapboxMap.addStyleImportFromJSON]. The
/// selector below lists the venue's floors plus a "Building" entry that
/// shows no floor, which lifts the clip layer and brings back Standard's own
/// 3D building. How the active floor reaches the style differs by platform:
///
/// * Web: like the GL JS example, the fragment registers the venue through
///   the style's `indoor` key and filters with `["is-active-floor", ...]`,
///   so the engine owns the active floor. mapbox_maps_flutter 3.0.0 exposes
///   that through [MapboxMap.indoor] (floor-state stream and `selectFloor`)
///   and the native floor selector ornament.
/// * iOS and Android: the native Maps SDKs only activate indoor data that
///   comes from Mapbox (Standard's `showIndoor`, gated behind an access
///   request), not a custom venue like this one. The mobile fragment
///   therefore declares an `activeFloor` config option and filters with
///   `["==", ["get", "floor_id"], ["config", "activeFloor"]]`, driven via
///   [MapboxMap.setStyleImportConfigProperty].
///
/// A 3D car from the SDK's model layer example is parked outside the
/// Messedamm entrance.
class IndoorMapPage extends StatefulWidget {
  const IndoorMapPage({super.key});

  @override
  State<IndoorMapPage> createState() => _IndoorMapPageState();
}

/// One floor of the venue, read from the `indoor-metadata` source.
class Floor {
  const Floor({required this.id, required this.name, required this.zIndex});

  final String id;
  final String name;
  final int zIndex;
}

class _IndoorMapPageState extends State<IndoorMapPage> {
  static const _importId = "indoor";

  /// Whether the engine's indoor machinery drives the active floor. Only
  /// Mapbox GL JS activates custom venues; see the class comment.
  static const _useNativeIndoor = kIsWeb;

  /// CityCube Berlin, both variants generated by
  /// tool/generate_citycube_fragment.py.
  static const _fragmentAsset = _useNativeIndoor
      ? 'assets/indoor/citycube_fragment.json'
      : 'assets/indoor/citycube_fragment_config.json';
  static const _activeFloorConfig = "activeFloor";
  static const _buildingFloorValue = "building";

  /// Show the Maps SDK's own floor selector ornament next to this page's
  /// selector where the engine drives the floors. Off by default to avoid
  /// two pickers for the same thing.
  static const _showNativeFloorSelector = false;

  /// 3D car parked in the car park east of the CityCube, across the
  /// forecourt from the Messedamm entrance, following the SDK's model layer
  /// example (https://docs.mapbox.com/flutter/maps/examples/model_layer/).
  static const _carModelId = "model-car-id";
  static const _carModelAsset = "asset://assets/models/sportcar.glb";
  static final _carPosition = Position(13.27238, 52.49969);

  // Camera read from the venue's `structure` feature. Kept as a single
  // instance so rebuilds never look like a viewport change to the MapWidget.
  CameraViewportState? _viewport;

  /// Same camera as [_viewport], for flying back after a detour.
  CameraOptions? _venueCamera;

  /// Berlin Brandenburg Airport, Terminal 1. Mapbox Standard ships indoor
  /// floor plans for airports; turning on its `showIndoor` option here shows
  /// the engine's built-in indoor mapping and native floor selector, as a
  /// preface to the custom venue.
  static final _airportCamera = CameraOptions(
    center: Point(coordinates: Position(13.5085, 52.3645)),
    zoom: 17,
    pitch: 50,
    bearing: 0,
  );
  static const _flightDurationMs = 6000;
  static const _basemapImportId = "basemap";

  /// True while showing the airport, where Standard's own indoor data and
  /// floor selector take over from this page's venue selector.
  bool _atAirport = false;

  MapboxMap? _mapboxMap;
  String? _fragment;
  List<Floor> _floors = const [];
  String? _defaultFloorId;

  /// Floor currently shown; null means no floor, i.e. the building view.
  String? _activeFloorId;

  /// On web the engine reports when it has recognised the venue; the config
  /// driven mobile path has no such step.
  bool _venueActive = !_useNativeIndoor;

  /// Set once the user picks the Building view, so the venue activating
  /// later does not snap back to the default floor.
  bool _buildingChosen = false;
  StreamSubscription<IndoorState>? _indoorSubscription;
  bool _indoorAdded = false;

  @override
  void initState() {
    super.initState();
    _loadFragment();
  }

  @override
  void dispose() {
    _indoorSubscription?.cancel();
    super.dispose();
  }

  Future<void> _loadFragment() async {
    final fragment = await rootBundle.loadString(_fragmentAsset);
    final style = jsonDecode(fragment) as Map<String, dynamic>;

    // The venue metadata has one `structure` feature, which carries the
    // camera, and one `floor` feature per level, ordered by z_index, with
    // the default flagged.
    final features =
        style["sources"]["indoor-metadata"]["data"]["features"] as List;
    final properties = features.map(
      (f) => f["properties"] as Map<String, dynamic>,
    );
    final structure = properties.firstWhere((p) => p["type"] == "structure");
    final viewport = CameraViewportState(
      center: Point(
        coordinates: Position(
          (structure["center_lon"] as num).toDouble(),
          (structure["center_lat"] as num).toDouble(),
        ),
      ),
      zoom: (structure["camera_zoom"] as num? ?? 19.5).toDouble(),
      pitch: (structure["camera_pitch"] as num? ?? 50).toDouble(),
      bearing: (structure["camera_bearing"] as num? ?? -15).toDouble(),
    );
    final floors = [
      for (final p in properties)
        if (p["type"] == "floor")
          Floor(
            id: p["id"] as String,
            name: p["name"] as String,
            zIndex: p["z_index"] as int,
          ),
    ]..sort((a, b) => b.zIndex.compareTo(a.zIndex));
    final defaultFloor = properties.firstWhere(
      (p) => p["type"] == "floor" && p["is_default"] == true,
    )["id"];

    setState(() {
      _viewport = viewport;
      _venueCamera = CameraOptions(
        center: viewport.center,
        zoom: viewport.zoom,
        pitch: viewport.pitch,
        bearing: viewport.bearing,
      );
      _fragment = fragment;
      _floors = floors;
      _defaultFloorId = defaultFloor as String;
      _activeFloorId = _defaultFloorId;
    });
    await _addIndoorImport();
  }

  Future<void> _onMapCreated(MapboxMap mapboxMap) async {
    _mapboxMap = mapboxMap;
    if (!_useNativeIndoor) return;

    // Mirror the engine's floor state so the selector stays in sync with
    // whatever selects a floor: this page, the native ornament, or the
    // engine picking the default floor once the venue is in view.
    _indoorSubscription = mapboxMap.indoor.indoorUpdates.listen((state) {
      // At the airport the stream describes Standard's airport floors, which
      // the native selector handles.
      if (!mounted || _atAirport) return;
      final venueActive = state.floors.isNotEmpty;
      setState(() {
        _venueActive = venueActive;
        _activeFloorId = state.selectedFloorId;
      });
      // The engine may report the venue before it settles on a floor; start
      // on the venue's default floor rather than the bare building.
      if (venueActive && state.selectedFloorId == null && !_buildingChosen) {
        mapboxMap.indoor.selectFloor(_defaultFloorId);
      }
    });

    await mapboxMap.indoorSelector.updateSettings(
      IndoorSelectorSettings(enabled: _showNativeFloorSelector),
    );
  }

  Future<void> _onStyleLoaded(StyleLoadedEventData _) => _addIndoorImport();

  /// Adds the indoor fragment once both the style and the asset are ready.
  /// Style-loaded fires again after the import is added, hence the guard.
  Future<void> _addIndoorImport() async {
    final mapboxMap = _mapboxMap;
    final fragment = _fragment;
    if (_indoorAdded || mapboxMap == null || fragment == null) return;
    _indoorAdded = true;

    await mapboxMap.addStyleImportFromJSON(
      _importId,
      fragment,
      config: _useNativeIndoor
          ? null
          : {_activeFloorConfig: _activeFloorId ?? _buildingFloorValue},
    );
    await _addCarModel(mapboxMap);
  }

  /// Adds the car as a style model, a one-point GeoJSON source and a
  /// [ModelLayer] that joins the two. Models render on every floor.
  Future<void> _addCarModel(MapboxMap mapboxMap) async {
    // Bundled models need the Flutter asset URI resolved to a native path.
    final carModelUri =
        await MapboxMapsOptions.getFlutterAssetPath(_carModelAsset) ??
        _carModelAsset;
    await mapboxMap.addStyleModel(_carModelId, carModelUri);

    await mapboxMap.addSource(
      GeoJsonSource(
        id: "carSourceId",
        data: json.encode(Point(coordinates: _carPosition)),
      ),
    );

    await mapboxMap.addLayer(
      ModelLayer(id: "modelLayer-car", sourceId: "carSourceId")
        ..modelId = _carModelId
        ..modelScale = [3, 3, 3]
        // Parked parallel to the building face, which has a bearing of 33°.
        ..modelRotation = [0, 0, 123]
        ..modelType = ModelType.COMMON_3D,
    );
  }

  /// Selects a floor, or no floor at all for the building view. On web the
  /// engine is asked and its indoor stream reports back; on mobile the
  /// import's config option is set directly.
  Future<void> _selectFloor(String? floorId) async {
    _buildingChosen = floorId == null;
    setState(() => _activeFloorId = floorId);
    final mapboxMap = _mapboxMap;
    if (mapboxMap == null) return;
    if (_useNativeIndoor) {
      await mapboxMap.indoor.selectFloor(floorId);
    } else {
      await mapboxMap.setStyleImportConfigProperty(
        _importId,
        _activeFloorConfig,
        floorId ?? _buildingFloorValue,
      );
    }
  }

  /// Flies to BER and switches on Standard's built-in indoor mapping plus
  /// the SDK's native floor selector ornament.
  Future<void> _flyToAirport() async {
    final mapboxMap = _mapboxMap;
    if (mapboxMap == null) return;
    setState(() => _atAirport = true);
    await mapboxMap.setStyleImportConfigProperty(
      _basemapImportId,
      "showIndoor",
      true,
    );
    await mapboxMap.indoorSelector.updateSettings(
      IndoorSelectorSettings(enabled: true),
    );
    await _flyTo(_airportCamera);
  }

  /// Flies back to the venue and hands floor selection back to this page.
  Future<void> _flyToVenue() async {
    final mapboxMap = _mapboxMap;
    if (mapboxMap == null) return;
    setState(() => _atAirport = false);
    await mapboxMap.indoorSelector.updateSettings(
      IndoorSelectorSettings(enabled: _showNativeFloorSelector),
    );
    await mapboxMap.setStyleImportConfigProperty(
      _basemapImportId,
      "showIndoor",
      false,
    );
    await _flyTo(_venueCamera);
  }

  Future<void> _flyTo(CameraOptions? camera) async {
    if (camera == null) return;
    await _mapboxMap?.flyTo(
      camera,
      MapAnimationOptions(duration: _flightDurationMs),
    );
  }

  @override
  Widget build(BuildContext context) {
    // Build the map only once the fragment is in hand. Rebuilding a MapWidget
    // before its platform view exists made mapbox_maps_flutter 3.0.0-rc.1
    // drop the initial viewport on Android.
    if (_fragment == null) {
      return Scaffold(
        appBar: AppBar(title: const Text("CityCube Berlin")),
        body: const Center(child: CircularProgressIndicator()),
      );
    }
    return Scaffold(
      appBar: AppBar(
        title: const Text("CityCube Berlin"),
        actions: [
          IconButton(
            icon: const Icon(Icons.place_outlined),
            tooltip: "Markers sample",
            onPressed: () => Navigator.of(
              context,
            ).push(MaterialPageRoute(builder: (_) => const MapPage())),
          ),
        ],
      ),
      body: Stack(
        children: [
          MapWidget(
            styleUri: MapboxStyles.STANDARD,
            viewport: _viewport!,
            onMapCreated: _onMapCreated,
            onStyleLoadedListener: _onStyleLoaded,
            onMapLoadErrorListener: (error) => debugPrint(
              "Indoor map load error: ${error.type} ${error.message}",
            ),
          ),
          // Floor selector: the venue's floors plus the building view.
          if (!_atAirport)
            Positioned(
              top: 16,
              right: 16,
              child: Card(
                clipBehavior: Clip.antiAlias,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    _FloorButton(
                      icon: Icons.apartment,
                      tooltip: "Building",
                      selected: _activeFloorId == null,
                      onPressed: () => _selectFloor(null),
                    ),
                    for (final floor in _floors)
                      _FloorButton(
                        label: floor.name,
                        selected: floor.id == _activeFloorId,
                        onPressed: () => _selectFloor(floor.id),
                      ),
                  ],
                ),
              ),
            ),
          // Camera flights: out to BER airport and back into the venue.
          Positioned(
            right: 16,
            bottom: 32,
            child: Card(
              clipBehavior: Clip.antiAlias,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  _FloorButton(
                    icon: Icons.flight_takeoff,
                    tooltip: "Fly to BER airport",
                    selected: false,
                    onPressed: _flyToAirport,
                  ),
                  _FloorButton(
                    icon: Icons.flight_land,
                    tooltip: "Fly back to CityCube",
                    selected: false,
                    onPressed: _flyToVenue,
                  ),
                ],
              ),
            ),
          ),
          if (!_venueActive && !_atAirport)
            Positioned(
              left: 16,
              bottom: 32,
              child: Card(
                child: Padding(
                  padding: const EdgeInsets.all(8),
                  child: Text(
                    "Waiting for the venue to activate…",
                    style: Theme.of(context).textTheme.bodySmall,
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

class _FloorButton extends StatelessWidget {
  const _FloorButton({
    this.label,
    this.icon,
    this.tooltip,
    required this.selected,
    required this.onPressed,
  });

  final String? label;
  final IconData? icon;
  final String? tooltip;
  final bool selected;
  final VoidCallback onPressed;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final color = selected ? scheme.onPrimary : scheme.onSurface;
    return Tooltip(
      message: tooltip ?? label ?? "",
      child: InkWell(
        onTap: onPressed,
        child: Container(
          width: 44,
          height: 44,
          alignment: Alignment.center,
          color: selected ? scheme.primary : null,
          child: icon != null
              ? Icon(icon, color: color, size: 22)
              : Text(
                  label!,
                  style: TextStyle(fontWeight: FontWeight.bold, color: color),
                ),
        ),
      ),
    );
  }
}
